// External Modules
import { Geist, Geist_Mono, Bebas_Neue, Poppins } from "next/font/google";
import "./styles/globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css"; 
import { config } from "@fortawesome/fontawesome-svg-core";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";

// Internal Modules
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

library.add(fab);

config.autoAddCss = false

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  subsets:['latin'],
  weight: '400'
})

const poppins = Poppins({
  subsets:['latin'],
  weight: '200'
})

export const metadata = {
  title: "Imperio Tickets",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>

        <Header />
        
          {children}

        <Footer />

        </div>
      </body>
    </html>
  );
}
